### ISSUE TITLE
제안서 리뷰

### ISSUE THREAD

**Issue by MisooKim2** [minchaechoe/PY202309-P#1]
1. 기능이 다소 부족해보입니다. 기능을 추가하거나 확장하십시오. (예: MBIT외의 사용자 취향이나 성별 등을 같이 활용하여 추천 등 )
- 변경 사항은 제안서는 수정하지 마시고, 1차 진척보고서에 반영하여 주시길 바랍니다

**Comment by minchaechoe** [comment]
확인 했습니다!
